mate-desktop/mate-settings-daemon

plugins/mpris/msd-mpris-manager.c

fix mpris plugin "vanish" function

---

plugins/a11y-keyboard/msd-a11y-keyboard-manager.c
plugins/mouse/msd-mouse-manager.c

plugins: G_GNUC_UNUSED in unused but needed variables

---

plugins/common/msd-osd-window.c
plugins/xsettings/msd-xsettings-manager.c

Related: https://github.com/mate-desktop/mate-power-manager/pull/246

Scale OSD size correctly on HiDPI displays

---

plugins/xrandr/msd-xrandr-manager.c

Add menu item to allow turning a monitor on or off from the popup menu. Borrow code from m-s-d display capplet to set geometry when a monitor is turned on. Turning on a monitor now works the same was as when turning it on but not reconfiguring it in mate-control-center's display capplet. The configuration capplet of course remains available from the popup if further configuration is needed, and all changes revert unless confirmed by the user in the "does the display look OK? dialog, same as from the capplet. Tooltip added to the enable/disable menu item to aid discoverability by users.

xrandr-applet-popup: enable turning monitors on an off

---

plugins/a11y-keyboard/msd-a11y-keyboard-manager.c
plugins/background/msd-background-manager.c
plugins/clipboard/msd-clipboard-manager.c
plugins/common/msd-input-helper.c
plugins/keyboard/msd-keyboard-manager.c
plugins/media-keys/msd-media-keys-manager.c
plugins/mouse/msd-mouse-manager.c
plugins/xrandr/msd-xrandr-manager.c
plugins/xsettings/wm-common.c

fix Gdk Deprecations

---

mate-settings-daemon/mate-settings-manager.c

origin commit:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/commit/36f32a3
Please test.

daemon: Stop using deprecated GSettings API

---

plugins/xrdb/msd-xrdb-manager.c

Fixes https://github.com/mate-desktop/mate-settings-daemon/pull/248#issuecomment-443527197

msd-xrdb-manager: realize the widget

---

.travis.yml

...and use docker-build from master

fix archlinux build on travis

---

.travis.yml

Fix make distcheck fail on debian. see #259

fixed make distcheck on debian

---

plugins/mouse/msd-locate-pointer.c

locate-pointer: Do not grab pointer button when trying to locate

---

mate-settings-daemon/mate-settings-manager.c
mate-settings-daemon/mate-settings-plugin-info.c

Please review and test, thanks.

fix deprecated g_type_class_add_private

---

plugins/common/msd-osd-window.c

plugins common: fix deprecated g_type_class_add_private

---

plugins/keyboard/msd-keyboard-manager.c
plugins/keyboard/msd-keyboard-plugin.c

Please review and test, thanks.

plugins keyboard: fix deprecated g_type_class_add_private

---

plugins/xrandr/msd-xrandr-manager.c

xrandr plugin: i18n dropdown menu

---

plugins/background/msd-background-manager.c
plugins/background/msd-background-plugin.c

plugins background: fix deprecated g_type_class_add_private

---

plugins/mouse/msd-mouse-manager.c
plugins/mouse/msd-mouse-plugin.c
plugins/mouse/msd-timeline.c

plugins mouse: fix deprecated g_type_class_add_private

---

plugins/a11y-keyboard/msd-a11y-keyboard-manager.c
plugins/a11y-keyboard/msd-a11y-keyboard-plugin.c
plugins/a11y-keyboard/msd-a11y-preferences-dialog.c

plugins a11y-keyboard: fix deprecated g_type_class_add_private

---

plugins/a11y-settings/msd-a11y-settings-manager.c
plugins/a11y-settings/msd-a11y-settings-plugin.c

plugins a11y-settings: fix deprecated g_type_class_add_private

---

plugins/mpris/Makefile.am
plugins/mpris/bus-watch-namespace.c
plugins/mpris/bus-watch-namespace.h
plugins/mpris/msd-mpris-manager.c

mpris: Use namespace instead of a whitelist for player names

---

plugins/housekeeping/msd-housekeeping-manager.c

Test
```
$ gsettings get org.mate.thumbnail-cache maximum-age
180
$ gsettings set org.mate.thumbnail-cache maximum-age 1
$ find ~/.cache/thumbnails -type f -name *.png -exec touch -d "-1 day" {} +
```
CPU profiling:
```patch
diff --git a/configure.ac b/configure.ac
index d4028cd..b4f3e45 100644
--- a/configure.ac
+++ b/configure.ac
@@ -401,7 +401,7 @@ AC_ARG_ENABLE(more-warnings,
AC_MSG_CHECKING(for more warnings)
if test "$GCC" = "yes" -a "$set_more_warnings" != "no"; then
AC_MSG_RESULT(yes)
-        CFLAGS="\
+        CFLAGS="-lprofiler \
-Wall \
-Wchar-subscripts -Wmissing-declarations -Wmissing-prototypes \
-Wnested-externs -Wpointer-arith \
```
```
CFLAGS="-lprofiler" LDFLAGS="-lprofiler" ./autogen.sh --prefix=/usr --enable-more-warnings && make V=1 && sudo make install …
```

housekeeping: Remove the warning about GTimeVal is deprecated

---

plugins/media-keys/msd-media-keys-manager.c

There is often a need for the user to increase the audio playback volume above
the volume level known as "100% volume".  While increasing the audio volume
above 100% can result in degraded audio quality, sometimes the audio was, for
example, originally recorded at an extremely low volume, and the user has no
other option to clearly hear the audio.  Unfortunately, most MATE applications
with volume controls do not allow the user to set the volume level above 100%.
For example, the main MATE Sound Preferences dialog lets you set the audio
volume beyond 100% (when possible), whereas the Volume Control Applet, Volume
Control status icon, and special "multimedia" volume control keys do not.  In
fact, if the user even tries to change the volume using any of the latter
methods, and the current …

Add setting for adjustment of audio volume above 100 per cent:  Part 3

---

plugins/xsettings/msd-xsettings-manager.c

Relax High DPI limits

---

plugins/smartcard/msd-smartcard-plugin.c

Although it looks like it's done, I don't know how to test it, maybe a smart card?

smartcard: migrate from dbus-glib to GDBus

---

mate-settings-daemon/Makefile.am
mate-settings-daemon/main.c
mate-settings-daemon/mate-settings-manager.c
mate-settings-daemon/mate-settings-manager.h
mate-settings-daemon/mate-settings-manager.xml
mate-settings-daemon/mate-settings-plugin-info.c

Pleae just test, but don't merge now.

msd: migrate from dbus-glib to GDBus
