mate-desktop/mate-settings-daemon

plugins/keyboard/msd-keyboard-xkb.c

Makes notifications for GSettings changes work again with GLib >= 2.43:
- fixes https://github.com/mate-desktop/mate-settings-daemon/issues/105
- fixes https://github.com/mate-desktop/mate-control-center/issues/178
Tested with the following schemas and keys:
- ```org.mate.peripherals-keyboard-xkb.general``` schema
- ```default-group``` (works only when ```group-per-window``` is ```true```)
- ```duplicate-leds```
- ```group-per-window```
- ```org.mate.peripherals-keyboard-xkb.kbd``` schema
- ```layouts``` - adding/removing Russian layout in addition to the default English (US) one (values: ```'us', 'ru'```)
- ```options``` - enabling/disabling Ctrl-Alt-Backspace (value: ```'terminate\tterminate:ctrl_alt_bksp'```)
@flexiondotorg @NiceandGently @infirit 
please test for any possible …

keyboard: connect to libmatekbd's GSettings before reading them

---

data/org.mate.peripherals-touchpad.gschema.xml.in.in
plugins/mouse/msd-mouse-manager.c

- Tuned default tap actions (to be consistent with Synaptic's default on 2-finger click and what's already there in other DEs)
- Added support for configurable 2-finger and 3-finger clicks
- Refactored code a bit to prevent tap actions from creating gsettings objects for each single device.

Touchpad support improvements

---

plugins/xrandr/Makefile.am

msd-xrandr is a custom icon, and it needs to be installed into the standard location, otherwise it's missing from icon themes other than mate.

xrandr: Install icon into hicolor directory

---

plugins/common/msd-osd-window.c

In GTK 3.21, the msd_osd_window_style_set segfaults on GtkStyle. This really should be updated for all GTK3 versions, so port it to GtkStyleContext. Just this one function for now as it stops the OSD crashes. Test built over GTK 3.21, no apparent problems and ran fine on GTK 3.18 as well, no apparent differences in theming using any theme from 3.18 with master.

Fix Gtk3.21 segfault using GtkStyleContext

---

data/org.mate.font-rendering.gschema.xml.in
plugins/xsettings/msd-xsettings-manager.c

Do this in order to match new default settings of fontconfig and therefore ensure out-of-the-box consistency of font rendering between GTK and non-GTK apps.
Fontconfig 2.11.95 (released 2016-04-06) changed its default hinting style setting to 'hintslight'.
Fontconfig maintainers have done it because:
1. 'hintslight' is clearly the best choice for LCD screens.
2. Many distributions (for example Ubuntu, which is known for good font rendering quality) had been patching fontconfig with this for many years.
So this change, in fact, just upstreams what many distributions had been doing anyway. It affects only these distributions, which hadn't been doing that, for example Arch.
Fontconfig settings are respected by most web browsers, PDF renderers and Qt apps. GTK apps, however, ignore fontconfig …

Use 'rgba' (LCD subpixel) antialiasing and 'hintslight' by default

---

plugins/common/msd-osd-window.c
plugins/common/msd-osd-window.h
plugins/media-keys/msd-media-keys-window.c
plugins/mouse/msd-locate-pointer.c
plugins/xsettings/msd-xsettings-manager.c

- complete port of media-keys to GtkStyleContext
- port msd-locate-pointer to GtkStyleContext
- add OSD style class to media-keys
- media-keys: do not use a hard coded setting for for all elements of the OSD window
- media-keys: fixes a -Wincompatible-pointer-types warning from previous commit
- mouse: fix deprecated gtk_style_context_get_background_color
- xsettings: fix build warning -Wdiscarded-qualifiers
Mainly our OSD windows use now osd settings from themes instead of old hard coded setting from gtk2 code which didn't work for gtk3.
If your theme does not support osd well than you can use this example setting.
```
MsdOsdWindow.background.osd {
border-radius: 10%;
}
MsdOsdWindow.background.osd.trough {
background-color: @osd_trough_bg;
border-style: solid;
border-width: 1px; …
```

port to GtkStyleContext and a few other fixes for warnings

---

plugins/background/msd-background-manager.c

Make sure m-s-d knows to draw the background unconditionally when used with transparent version of Caja for GTK 3.21 or later.  Fix background changing with or without caja running. Remove all references to Caja from GTK 3.21 or later builds, remove resulting unused variable. Note that fading between backgrounds does not work in GTK 3.21 in this PR nor in master with caja not running, this appears to be an issue in mate-desktop with GTK 3.21.
Apply all of this only to GTK 3.21 or later builds, same as for https://github.com/mate-desktop/caja/pull/602 in Caja. These are meant to be used together, and not to disturb the perfectly good background handling in GTK 3.20 or earlier builds

GTK 3.21: Fix background changing, caja startup

---

data/org.mate.peripherals-touchpad.gschema.xml.in
plugins/mouse/msd-mouse-manager.c

This adds some new settings for touchpad: handedness (right/left/follow mouse), motion-acceleration and motion-threshold.
Handedness setting has the default value to follow the corresponding mouse setting, so the default behavior will be the same.
Motion settings previously were applied to both mouse and touchpad at the same time once you set it in mate-mouse-properties (or in dconf-editor). Now touchpad settings are separated from mouse ones, and they have to be set separately.
@clefebvre @flexiondotorg @raveit65 @XRevan86 @sc0w @lukefromdc
Please test it guys if you can.

new touchpad settings

---

plugins/common/msd-osd-window.c

Fix for https://github.com/mate-desktop/mate-settings-daemon/issues/163
Use same function to get width and height as in the composited case. gtk_widget_get_allocated_width/height seems to cause a lot of problems in GTK3

OSD: fix rendering on noncomposited desktop

---

plugins/common/msd-input-helper.c
plugins/mouse/msd-mouse-manager.c

This is backported from https://github.com/linuxmint/cinnamon-settings-daemon/pull/131 (big thanks to @whot for this).
@clefebvre @flexiondotorg @raveit65 @XRevan86 @sc0w @lukefromdc
Please test it guys if you can. You'll need libinput driver for Xorg installed and taking priority over evdev and Synaptics. You can use ```xinput``` tool to check device properties and their values. For example, here's how my old mouse is shown:
```
monsta@asylum ~ $ xinput --list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Logitech USB-PS/2 Optical Mouse         	id=8	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
↳ Virtual core XTEST keyboard …
```

add libinput support for mouse and touchpad

---

plugins/background/msd-background-manager.c

This fixes directory background drawing in #506, fixes compiz-reloaded/compiz#40 (desktop background issues with Compiz 0.8.x) and fixes background fading.
Caja now draws the desktop background again and the gap in code between GTK+ 3.22 and previous versions is removed.
Other parts of the change: mate-desktop/mate-desktop#249, mate-desktop/caja#731.

Fixes for background drawing

---

plugins/keyboard/msd-keyboard-xkb.c

This menu was not noticed back in 2015 when support for custom panel menu themes was added, as I had only one keyboard layout installed. Testing the recent flags work in libmakekbd revealed this menu, which in my theme mismatched all other panel menus as the theme support had not been added

keyboard plugin: apply panel menu theme to popup menu

---

plugins/keybindings/msd-keybindings-manager.c

This allows mate-settings-daemon to honor global keybindings whenever
a different application has keybindings that seem conflicting, but are
usually not.
For example, an application defining a `Super_L` keybinding
and MATE having defining a shortcut that uses the `<Mod4>` key. They are
the same physical keyboard, but one is a modifier and the other is not.
Without requesting keyboard reports from other windows, the `<Mod4>`
shortcuts are swallowed whenever there is a `Super_L` shortcut
elsewhere.

Request keyboard event reports from global keybindings of other windows

---

plugins/keybindings/msd-keybindings-manager.c

When setting `KeyPressMask` as a reportable event for all windows, the
keybinding for `Fn+F7` in Xrandr seems to fail. This change adds, rather
than overrides, the `KeyPressMask` as a reportable event for the
corresponding window.
Fixes #180

Fix Xrandr applet dying on restart

---

plugins/media-keys/msd-media-keys-manager.c

avoid deprecated:
gdk_screen_get_monitor_geometry
gdk_screen_get_monitor_at_point

gtk 3.22: avoid deprecated gdk_screen_get_monitor... functions:

---

plugins/a11y-keyboard/msd-a11y-preferences-dialog.c
plugins/xsettings/msd-xsettings-manager.c

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1517547

Fix: big fonts by default with "org.mate.desktop.font-rendering.dpi"

---

plugins/background/msd-background-manager.c
plugins/common/msd-osd-window.c

The work began with:
https://github.com/mate-desktop/mate-settings-daemon/commit/788babedafaf59d8b7a36cb0ef3b0b1f0e5f732c
This commit reverts:
https://github.com/mate-desktop/mate-settings-daemon/commit/7f887e614812ccb86f5d784e2db58bede8daa712
And it applies an alternative to fix the deprecated functions:
gdk_screen_get_width
gdk_screen_get_height

WidthOfScreen and HeightOfScreen implementation

---

plugins/mpris/msd-mpris-manager.c

passing argument 3 of ‘g_queue_find_custom’ from incompatible pointer type

msd-mpris-manager.c: Fix build warning:

---

plugins/a11y-keyboard/msd-a11y-preferences-dialog.c
plugins/xsettings/msd-xsettings-manager.c

When setting `GDK_SCALE=2` and `GDK_DPI_SCALE=0.5` as env variables, m-s-d will now scale the mouse pointer and the font-rendering DPI.
This is part of multiple pull requests:
* mate-desktop/mate-settings-daemon/pull/208
* mate-desktop/mate-control-center/pull/325
* mate-desktop/mate-panel/pull/710
* ubuntu-mate/mate-hud/pull/18
* ubuntu-mate/mate-tweak/pull/37

Add support for HiDPI displays

---

plugins/keybindings/msd-keybindings-manager.c
plugins/media-keys/msd-media-keys-manager.c

This changes how the media-keys manager determines successful
key-bindings from KeyRelease to KeyPress so that it does not conflict
with third-party applications that want to use modifier keys as global
key-bindings. We've already done this change for general keybindings and
marco.
It also cleans up a bunch of deprecation warnings.
Related:
* ubuntu-mate/mate-menu/pull/33
* solus-project/brisk-menu/pull/88

Prevent media-keys bindings from swallowing modifier keys

---

plugins/xrandr/msd-xrandr-manager.c

Xrandr applet: fix popup menu

---

plugins/xsettings/msd-xsettings-manager.c

When enabling org.mate.interface window-scaling-factor-qt-sync (default), m-s-d will attempt to set QT_SCALE_FACTOR during the init phase.
When disabled, the user can then choose to control this env var elsewhere.
* Requires mate-desktop/mate-desktop/pull/320
* Fixes mate-desktop/mate-session-manager/issues/158

Make setting QT_SCALE_FACTOR optional.

---

plugins/xrandr/msd-xrandr-manager.c

Add menuitem for mirroring same output to all displays
Very useful for laptop users running projectors in public settings. Quite common to see people fumble with trying to get mirroring a laptop to a projector or a big screen working under pressure. This enables it with a single click.

xrandr-applet-popup: add item to mirror displays

---

plugins/xsettings/msd-xsettings-manager.c

Requires https://github.com/mate-desktop/mate-desktop/pull/332 to add the necessary gsettings key in "interface."  Default is "enabled" to avoid any change in expected behavior with a default install.

xsettings: add setting to enable/disable primary paste from middlemouse

---

plugins/xrandr/msd-xrandr-manager.c

Remove an unused function in msd-xrandr-manager.c left over from previous work there

Xrandr: remove an unused function

---

plugins/a11y-keyboard/msd-a11y-keyboard-manager.c

Allow to configure whether modifier latching should be enabled when enabling sticky keys.
See https://github.com/mate-desktop/mate-desktop/pull/335 for the new setting and https://github.com/mate-desktop/mate-control-center/pull/374 for the UI.

Add support for org.mate.accessibility-keyboard.stickykeys-latch-to-lock

---

plugins/media-keys/acme.h
plugins/media-keys/msd-media-keys-manager.c

Using hard-coded keys.
This requires new keycodes added to X.org in:
https://bugs.freedesktop.org/show_bug.cgi?id=31300
Ported from gnome-settings-daemon:
https://github.com/GNOME/gnome-settings-daemon/commit/1c8f64d1dc6beb7d27a6dce74fa29e27e8c34583

media-keys: Add support for XF86TouchpadOn/Off

---

plugins/media-keys/msd-media-keys-manager.c

This PR is ported from gnome-settings-daemon:
https://github.com/GNOME/gnome-settings-daemon/commit/fe41be4f980dee86a594105398a63cb3e1b4c689

media-keys: Simplify touchpad OSD

---

configure.ac
data/Makefile.am
data/org.mate.SettingsDaemon.plugins.rfkill.gschema.xml.in
mate-settings-daemon/Makefile.am
mate-settings-daemon/mate-settings-bus.c
mate-settings-daemon/mate-settings-bus.h
plugins/Makefile.am
plugins/media-keys/acme.h
plugins/media-keys/msd-media-keys-manager.c
plugins/rfkill/61-mate-settings-daemon-rfkill.rules
plugins/rfkill/Makefile.am
plugins/rfkill/msd-rfkill-manager.c
plugins/rfkill/msd-rfkill-manager.h
plugins/rfkill/msd-rfkill-plugin.c
plugins/rfkill/msd-rfkill-plugin.h
plugins/rfkill/rfkill-glib.c
plugins/rfkill/rfkill-glib.h
plugins/rfkill/rfkill.h
plugins/rfkill/rfkill.mate-settings-plugin.in
po/POTFILES.in

Add support for the XF86Bluetooth and XF86WLAN media keys. The first one will toggle Bluetooth on/off, as the Bluetooth panel does, the latter one will toggle the global software killswitch.
The reasoning XF86WLAN media key toggling the global software killswitch is that:
- we don't have a killswitch for only WiFi
- there are very very few laptops with a UWB killswitch button, if anyone actually remembers what UWB actually is
- there are no XF86 keys for the global killswitch, so they usually get mislabeled as the WLAN killswitch
Ported from gnome-settings-daemon:
from https://github.com/GNOME/gnome-settings-daemon/commit/3fa0f7260a6864dfe67bdbd82b22b168e1e66457
This feature requires rfkill plugin support. See:
rfkill: Add RFKill support plugin on Linux systems
from …

media-keys: Add support for Killswitch media keys

---

plugins/media-keys/msd-media-keys-manager.c
plugins/media-keys/msd-media-keys-window.c
plugins/media-keys/msd-media-keys-window.h
plugins/media-keys/test-media-window.c

Screen brightness OSD has been moved from m-s-d to m-p-m, see:
https://github.com/mate-desktop/mate-power-manager/commit/4fd2ae34e50e63ef562356f804dbdea81341f4e2
So remove test for brightness OSD icons in m-s-d.
Sence brightness OSD has been moved to m-p-m, there is no any situation to control show_level in msd_media_keys_window_set_action_custom, should remove this argument.

Remove unuseful argument and test for screen brightness OSD icons

---

plugins/media-keys/acme.ui
plugins/media-keys/msd-media-keys-manager.c
plugins/media-keys/msd-media-keys-window.c
plugins/media-keys/msd-media-keys-window.h
plugins/media-keys/test-media-window.c

Add labels for the rfkill and touchpad OSD, which should hopefully make the icons a bit clearer. Add test for rfkill OSD icons too.

media-keys: Add labels for the rfkill and touchpad OSD, and test for rfkill OSD icons 

---

plugins/media-keys/msd-media-keys-manager.c

As discussed in:
https://bugzilla.gnome.org/show_bug.cgi?id=644537#c4

media-keys: Don't show a level when muted

---

plugins/media-keys/acme.h
plugins/media-keys/msd-media-keys-manager.c
plugins/media-keys/test-media-window.c

Some laptops like thinkpad have a display switch mode hotkey. This is bound by default to XF86Display. Add OSD to give people a visual feed back to switch display mode.
The hotkey is like this:
looking the OSD bellow:
How to test:
Press the F7 hotkey on thinkpad with connecting more than one screen. Or execute:
```php
xdotool key XF86Display
```

media-keys: Add support for display switch OSD

---

plugins/common/msd-osd-window.c
plugins/media-keys/msd-media-keys-window.c

Refer to some gnome commits:
https://github.com/GNOME/gnome-settings-daemon/commit/bacb20270cde60cc71bff6723336e50acc3935b2
https://github.com/GNOME/gnome-settings-daemon/commit/a03c072a8241d4d481ee94e5e1ffd829e85271f5
Before changed:
After changed:

Tweak the OSD a bit smaller

---

plugins/xrdb/msd-xrdb-manager.c

Seems `gtk_widget_ensure_style` is useless, according to the documentation:
https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-ensure-style
> Not a very useful function; most of the time, if you want the style, the widget is realized, and realized widgets are guaranteed to have a style already.

msd-xrdb-manager.c: avoid deprecated 'gtk_widget_ensure_style'

---

plugins/media-keys/msd-media-keys-manager.c

• Removes if-elif-else ladder that determines which calculator application to open when XF86Calculator is pressed
• Instead, when XF86Calculator is pressed, m-s-d executes the command listed in the default calculator application schema (defined in commit https://github.com/mate-desktop/mate-desktop/pull/341/commits/328116089489c674bad3b17bc69c267865968d24), And this PR is dependent on it
• Relevant PR:
https://github.com/mate-desktop/mate-desktop/pull/341

media-keys: Execute default calculator application defined by schema

---

plugins/housekeeping/msd-ldsm-dialog.c

```
/usr/include/glib-2.0/glib/gmacros.h:366:42: warning: division ‘sizeof (gchar ** {aka char **}) / sizeof (gchar * {aka char *})’ does not compute the number of array elements [-Wsizeof-pointer-div]
366 | #define G_N_ELEMENTS(arr)  (sizeof (arr) / sizeof ((arr)[0]))
|                                          ^
msd-ldsm-dialog.c:163:25: note: in expansion of macro ‘G_N_ELEMENTS’
163 |         for (i = 0; i < G_N_ELEMENTS (settings_list); i++) {
|                         ^~~~~~~~~~~~
```

Avoid build warning

---

configure.ac
plugins/a11y-keyboard/Makefile.am
plugins/keyboard/Makefile.am
plugins/keyboard/msd-keyboard-manager.c
plugins/media-keys/Makefile.am

The X server hasn't implemented it in over 10 years.
And it was dropped from debian since a long time.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=568285
fixes https://github.com/mate-desktop/mate-settings-daemon/issues/284

plugins: drop libXxf86 dependency

---

mate-settings-daemon/mate-settings-plugin.h

This macro can used to fix deprecated g_type_class_add_private in some plugins/*/*-plugin.c files.

add new macro MATE_SETTINGS_PLUGIN_REGISTER_WITH_PRIVATE

---

data/org.mate.SettingsDaemon.plugins.media-keys.gschema.xml.in
plugins/media-keys/msd-media-keys-manager.c

As discussed in https://github.com/mate-desktop/mate-media/pull/138, which makes use of this value as well.

Change media-keys volume-step default from 6 to 5

---

.travis.yml
NEWS
configure.ac
data/Makefile.am
data/org.mate.peripherals-keyboard.gschema.xml.in
data/org.mate.peripherals-mouse.gschema.xml.in
data/org.mate.peripherals-touchpad.gschema.xml.in
plugins/mouse/msd-mouse-manager.c
po/POTFILES.in

Currently libinput supports Adaptive and Flat acceleration profiles. We
can use these to change mouse behavior. Synaptic touchpads are not
supported through libinput, so they will not be affected by this change.
There does not seem to be a defined behavior for a Default acceleration
profile, so it's not included.
Multi-part patch:
* https://github.com/mate-desktop/mate-desktop/pull/407
* https://github.com/mate-desktop/mate-settings-daemon/pull/293
* https://github.com/mate-desktop/mate-control-center/pull/494

mouse: Add acceleration profiles

---

data/mate-settings-daemon.desktop.in.in

Autostart desktop files are hidden from the Startup Applications capplet. This pull request ensures that MATE Settings Daemon is not presented as an item that users can disable. See also:
* https://github.com/mate-desktop/mate-session-manager/pull/213

Hide MATE Settings Daemon from Startup Applications capplet

---

mate-settings-daemon/mate-settings-manager.c
plugins/a11y-keyboard/msd-a11y-keyboard-manager.c
plugins/a11y-keyboard/msd-a11y-preferences-dialog.c
plugins/a11y-settings/msd-a11y-settings-manager.c
plugins/clipboard/msd-clipboard-manager.c
plugins/dummy/msd-dummy-manager.c
plugins/housekeeping/msd-housekeeping-manager.c
plugins/housekeeping/msd-ldsm-dialog.c
plugins/keybindings/msd-keybindings-manager.c
plugins/keyboard/msd-keyboard-manager.c
plugins/media-keys/msd-media-keys-manager.c
plugins/mouse/msd-mouse-manager.c
plugins/mpris/msd-mpris-manager.c
plugins/rfkill/msd-rfkill-manager.c
plugins/sound/msd-sound-manager.c
plugins/typing-break/msd-typing-break-manager.c
plugins/xrandr/msd-xrandr-manager.c
plugins/xrdb/msd-xrdb-manager.c
plugins/xsettings/msd-xsettings-manager.c

Fixes the warnings:
[mate-settings-daemon-Wredundant-decls.txt](https://github.com/mate-desktop/mate-settings-daemon/files/3964304/mate-settings-daemon-Wredundant-decls.txt)

avoid redundant redeclarations

---

configure.ac

Since D-Bus 1.9.18 configuration files installed by third-party should
go in share/dbus-1/system.d. The old location is for sysadmin overrides.
Please **merge with #303**

Default DBUS_SYS_DIR to ${datadir}/dbus-1/system.d

---

plugins/housekeeping/msd-ldsm-dialog.c

housekeeping: Fix iconname of mate-disk-usage-analyzer

---

plugins/housekeeping/msd-disk-space.c
plugins/housekeeping/msd-ldsm-trash-empty.c
plugins/keyboard/msd-keyboard-xkb.c
plugins/xsettings/msd-xsettings-manager.c

```
< msd-ldsm-trash-empty.c:236:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
<   236 | trash_empty_start ()
<       | ^~~~~~~~~~~~~~~~~
< msd-ldsm-trash-empty.c:343:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
<   343 | trash_empty_show_confirmation_dialog ()
<       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
< msd-disk-space.c:587:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
<   587 | msd_ldsm_get_config ()
<       | ^~~~~~~~~~~~~~~~~~~
< msd-keyboard-xkb.c:166:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
<   166 | popup_menu_launch_capplet ()
<       | ^~~~~~~~~~~~~~~~~~~~~~~~~
< msd-keyboard-xkb.c:198:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
< …
```

Remove warnings about function declaration isn’t a prototype

---

plugins/mouse/msd-mouse-manager.c

```
< msd-mouse-manager.c:1363:35: warning: absolute value function ‘abs’ given an argument of type ‘glong’ {aka ‘long int’} but has parameter of type ‘int’ which may cause truncation of value [-Wabsolute-value]
<  1363 |                         ptr[0] = -abs(ptr[0]);
<       |                                   ^~~
< msd-mouse-manager.c:1364:35: warning: absolute value function ‘abs’ given an argument of type ‘glong’ {aka ‘long int’} but has parameter of type ‘int’ which may cause truncation of value [-Wabsolute-value]
<  1364 |                         ptr[1] = -abs(ptr[1]);
<       |                                   ^~~
< msd-mouse-manager.c:1366:34: warning: absolute value function ‘abs’ given an argument of type ‘glong’ {aka ‘long int’} but has parameter of type ‘int’ which may cause …
```

mouse: Remove warnings about absolute value function for long

---

plugins/media-keys/Makefile.am

`dbus-binding-tool` also displays this warning, that should disappear after porting to `gdbus-codegen`.

build: Using --header and --body at the same time is deprecated

---

plugins/a11y-keyboard/msd-a11y-keyboard-manager.c

```
$ ./autogen.sh --prefix=/usr --enable-compile-warnings=maximum --enable-debug && make &> make.log
$ grep -A 2 Wimplicit-function-declaration make.log
msd-a11y-keyboard-manager.c:410:17: warning: implicit declaration of function 'd' [-Wimplicit-function-declaration]
410 |                 d ("cancelling AccessX request");
|                 ^
```
culprit #325

msd-a11y-keyboard-manager: implicit declaration of function 'd'

---

plugins/media-keys/msd-media-keys-manager.c

```
msd-media-keys-manager.c: In function 'do_sound_action':
/usr/include/glib-2.0/glib/gmacros.h:813:63: warning: comparison of unsigned expression in '< 0' is always false [-Wtype-limits]
813 | #define CLAMP(x, low, high)  (((x) > (high)) ? (high) : (((x) < (low)) ? (low) : (x)))
|                                                               ^
msd-media-keys-manager.c:783:24: note: in expansion of macro 'CLAMP'
783 |                        CLAMP (100 * volume / (volume_max - volume_min), 0, 100),
|                        ^~~~~
```

msd-media-keys-manager: comparison of unsigned expression in '< 0' is always false

---

mate-settings-daemon/main.c
mate-settings-daemon/mate-settings-plugin-info.c
plugins/a11y-keyboard/msd-a11y-keyboard-manager.c
plugins/a11y-keyboard/msd-a11y-preferences-dialog.c
plugins/a11y-settings/msd-a11y-settings-manager.c
plugins/background/msd-background-manager.c
plugins/datetime/system-timezone.c
plugins/housekeeping/msd-disk-space.c
plugins/housekeeping/msd-housekeeping-manager.c
plugins/housekeeping/msd-ldsm-trash-empty.c
plugins/keybindings/msd-keybindings-manager.c
plugins/keyboard/msd-keyboard-xkb.c
plugins/media-keys/msd-media-keys-manager.c
plugins/mouse/msd-locate-pointer.c
plugins/mpris/bus-watch-namespace.c
plugins/mpris/msd-mpris-manager.c
plugins/rfkill/msd-rfkill-manager.c
plugins/smartcard/msd-smartcard-plugin.c
plugins/sound/msd-sound-manager.c
plugins/xrandr/msd-xrandr-manager.c
plugins/xrdb/msd-xrdb-manager.c
plugins/xsettings/msd-xsettings-manager.c

mark parameters as unused with `G_GNUC_UNUSED` called by `G_CALLBACK` inside `g_signal_connect`

add G_GNUC_UNUSED in some unused parameters

---

mate-settings-daemon/mate-settings-plugin-info.c

```
mate-settings-plugin-info.c: In function 'plugin_enabled_cb':
mate-settings-plugin-info.c:269:44: warning: unused parameter 'settings' [-Wunused-parameter]
269 | plugin_enabled_cb (GSettings              *settings,
|                    ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
```
Test: disable/enable msd plugin
```
$ gsettings get org.mate.SettingsDaemon.plugins.housekeeping active
true
$ gsettings set org.mate.SettingsDaemon.plugins.housekeeping active false
```

mate-settings-plugin-info: unused parameter 'settings'

---

mate-settings-daemon/main.c

Test: enable debugging
```
$ gsettings get org.mate.debug mate-settings-daemon
false
$ gsettings set org.mate.debug mate-settings-daemon true
```

main: Do not override detailed_signal for debugging

---

plugins/a11y-keyboard/msd-a11y-keyboard-manager.c

This allows a customizable and possibly different beep sequence when a togglekey is enabled or disabled.  This is very useful for the user to know for sure whether the feature got enabled or disabled.
Back in the days of buzzers, XKB was supposed to use different sounds for each of those, but this is no longer the case now in the vast majority of setups the beeps are intercepted and use a single recorded sound.
So instead provide an implementation for togglekeys on our end by listening to the `XkbIndicatorStateNotify` events, and provide options to control the feedback.  The XKB implementation is still available, and used by default for now (see https://github.com/mate-desktop/mate-desktop/pull/451).
This depends on https://github.com/mate-desktop/mate-desktop/pull/451, but I didn't bump …

Add suport for customizing togglekeys feedback

---

plugins/media-keys/msd-media-keys-manager.c

```
msd-media-keys-manager.c:1072:17: warning: 'GTimeVal' is deprecated: Use 'GDateTime' instead [-Wdeprecated-declarations]
1072 |                 GTimeVal tv;
|                 ^~~~~~~~
```

msd-media-keys-manager: 'GTimeVal' is deprecated

---

plugins/clipboard/msd-clipboard-manager.c
plugins/housekeeping/msd-disk-space.c
plugins/keyboard/msd-keyboard-xkb.c
plugins/mouse/msd-locate-pointer.c

```
msd-clipboard-manager.c:472:22: warning: declaration of 'targets' shadows a previous local [-Wshadow]
472 |                 Atom targets[3];
|                      ^~~~~~~
--
msd-disk-space.c:638:36: warning: declaration of 'settings' shadows a global declaration [-Wshadow]
638 | msd_ldsm_update_config (GSettings *settings ,
|                         ~~~~~~~~~~~^~~~~~~~
--
msd-keyboard-xkb.c:262:44: warning: declaration of 'icon' shadows a global declaration [-Wshadow]
262 | status_icon_popup_menu_cb (GtkStatusIcon * icon, guint button, guint time)
|                            ~~~~~~~~~~~~~~~~^~~~
--
msd-locate-pointer.c:54:45: warning: declaration of 'data' shadows a global declaration [-Wshadow]
54 | locate_pointer_paint (MsdLocatePointerData *data,
| …
```

Remove warning -Wshadow

---

plugins/a11y-keyboard/msd-a11y-keyboard-manager.c

```
plugins/a11y-keyboard/msd-a11y-keyboard-manager.c:206:31: warning: Either the condition 'desc!=NULL' is redundant or there is possible null pointer dereference: desc. [nullPointerRedundantCheck]
g_return_val_if_fail (desc->ctrls != NULL, NULL);
^
plugins/a11y-keyboard/msd-a11y-keyboard-manager.c:199:18: note: Assuming that condition 'desc!=NULL' is not redundant
if (desc != NULL) {
^
plugins/a11y-keyboard/msd-a11y-keyboard-manager.c:206:31: note: Null pointer dereference
g_return_val_if_fail (desc->ctrls != NULL, NULL);
^
```

cppcheck warning: null pointer redundant check

---

plugins/common/msd-input-helper.c
plugins/common/msd-keygrab.c
plugins/xrandr/msd-xrandr-manager.c

```
plugins/common/msd-input-helper.c:123:25: style: Condition 'device_info!=NULL' is always true [knownConditionTrueFalse]
if (device_info != NULL)
^
plugins/common/msd-input-helper.c:111:25: note: Assuming that condition 'device_info==NULL' is not redundant
if (device_info == NULL)
^
plugins/common/msd-input-helper.c:123:25: note: Condition 'device_info!=NULL' is always true
if (device_info != NULL)
^
```
```
plugins/xrandr/msd-xrandr-manager.c:2057:39: style: Condition 'config==NULL' is always false [knownConditionTrueFalse]
if (!config || config == NULL){
^
plugins/xrandr/msd-xrandr-manager.c:2057:21: note: Assuming that condition '!config' is not redundant
if (!config || config == NULL){
^
plugins/xrandr/msd-xrandr-manager.c:2057:39: note: Condition 'config==NULL' is always false
if …
```

cppcheck warning: known condition is always true

---

plugins/keyboard/msd-keyboard-manager.c
plugins/media-keys/msd-media-keys-manager.c
plugins/xrandr/msd-xrandr-manager.c

```
plugins/keyboard/msd-keyboard-manager.c:218:23: style: Variable 'rate' is assigned a value that is never used. [unreadVariable]
rate          = g_settings_get_int   (settings, KEY_RATE);
^
plugins/keyboard/msd-keyboard-manager.c:219:23: style: Variable 'delay' is assigned a value that is never used. [unreadVariable]
delay         = g_settings_get_int   (settings, KEY_DELAY);
^
plugins/media-keys/msd-media-keys-manager.c:603:31: style: Variable 'score' is assigned a value that is never used. [unreadVariable]
score = SCORE_HAS_MEDIA;
^
plugins/xrandr/msd-xrandr-manager.c:815:37: style: Variable 'best_width' is assigned a value that is never used. [unreadVariable]
best_width  = w;
^
plugins/xrandr/msd-xrandr-manager.c:816:37: style: Variable 'best_height' is assigned a value that is …
```

cppcheck warning: Variable is assigned a value that is never used

---

configure.ac
mate-settings-daemon/main.c
mate-settings-daemon/mate-settings-manager.c
mate-settings-daemon/mate-settings-plugin-info.c

-Wconversion 3
-Wsign-conversion 4
```
mate-settings-plugin-info.c:248:40: warning: conversion to ‘guint’ {aka ‘unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
248 |                 info->priv->priority = priority;
|                                        ^~~~~~~~
--
/usr/include/glib-2.0/glib/gmacros.h:808:14: warning: conversion from ‘int’ to ‘signed char:1’ changes value from ‘1’ to ‘-1’ [-Wconversion]
808 | #define TRUE (!FALSE)
|              ^
--
/usr/include/glib-2.0/glib/gmacros.h:808:14: warning: conversion from ‘int’ to ‘signed char:1’ changes value from ‘1’ to ‘-1’ [-Wconversion]
808 | #define TRUE (!FALSE)
|              ^
--
mate-settings-plugin-info.c:497:26: warning: conversion to ‘int’ from ‘guint’ {aka ‘unsigned int’} may change the sign of …
```

mate-settings-daemon: Remove -Wconversion -Wsign-conversion -Wcast-function-type warnings

---

plugins/sound/msd-sound-manager.c

```
plugins/sound/msd-sound-manager.c:48:20: style: struct member 'MsdSoundManagerPrivate::settings' is never used. [unusedStructMember]
GSettings *settings;
^
plugins/sound/msd-sound-manager.c:49:16: style: struct member 'MsdSoundManagerPrivate::monitors' is never used. [unusedStructMember]
GList* monitors;
^
```

cppcheck warning: struct member is never used

---

plugins/housekeeping/msd-housekeeping-manager.c

```
msd-housekeeping-manager.c: In function ‘purge_thumbnail_cache’:
msd-housekeeping-manager.c:203:32: warning: cast between incompatible function types from ‘void (*)(void *)’ to ‘void (*)(void *, void *)’ [-Wcast-function-type]
203 |         g_list_foreach (files, (GFunc) thumb_data_free, NULL);
|                                ^
```

housekeeping: Remove warning -Wcast-function-type

---

plugins/media-keys/msd-media-keys-manager.c
plugins/media-keys/msd-media-keys-window.c
plugins/media-keys/msd-media-keys-window.h

```
msd-media-keys-manager.c: In function ‘update_dialog’:
msd-media-keys-manager.c:680:49: warning: conversion to ‘int’ from ‘guint’ {aka ‘unsigned int’} may change the sign of the result [-Wsign-conversion]
680 |                                                 volume);
|                                                 ^~~~~~
msd-media-keys-manager.c: In function ‘do_sound_action’:
msd-media-keys-manager.c:726:23: warning: conversion to ‘guint’ {aka ‘unsigned int’} from ‘gint’ {aka ‘int’} may change the sign of the result [-Wsign-conversion]
726 |         volume_step = g_settings_get_int (manager->priv->settings, "volume-step");
|                       ^~~~~~~~~~~~~~~~~~
msd-media-keys-manager.c:729:31: warning: conversion to ‘guint’ {aka ‘unsigned int’} from ‘gint32’ {aka ‘int’} may …
```

media-keys: Remove conversion warnings

---

plugins/background/msd-background-manager.c

```
msd-background-manager.c: In function ‘on_screen_size_changed’:
msd-background-manager.c:258:57: warning: conversion to ‘guint’ {aka ‘unsigned int’} from ‘gint’ {aka ‘int’} may change the sign of the result [-Wsign-conversion]
258 |  gchar *old_size = g_list_nth_data (manager->scr_sizes, scr_num);
|                                                         ^~~~~~~
```
```
msd-background-manager.c: In function ‘draw_bg_after_session_loads’:
/usr/include/glib-2.0/gobject/gsignal.h:493:5: warning: conversion from ‘gulong’ {aka ‘long unsigned int’} to ‘guint’ {aka ‘unsigned int’} may change value [-Wconversion]
493 |     g_signal_connect_data ((instance), (detailed_signal), (c_handler), (data), NULL, (GConnectFlags) 0)
|     ^~~~~~~~~~~~~~~~~~~~~
```

background: Remove conversion warnings

---

plugins/xsettings/msd-xsettings-manager.c

```
msd-xsettings-manager.c: In function ‘scale_change_workarounds’:
msd-xsettings-manager.c:577:51: warning: cast between incompatible function types from ‘gboolean (*)(gboolean)’ {aka ‘int (*)(int)’} to ‘gboolean (*)(void *)’ {aka ‘int (*)(void *)’} [-Wcast-function-type]
577 |                         g_timeout_add_seconds (1, (GSourceFunc) delayed_toggle_bg_draw, (gpointer) FALSE);
|                                                   ^
msd-xsettings-manager.c:578:51: warning: cast between incompatible function types from ‘gboolean (*)(gboolean)’ {aka ‘int (*)(int)’} to ‘gboolean (*)(void *)’ {aka ‘int (*)(void *)’} [-Wcast-function-type]
578 |                         g_timeout_add_seconds (2, (GSourceFunc) delayed_toggle_bg_draw, (gpointer) TRUE);
| …
```

xsettings: Remove warning -Wcast-function-type

---

plugins/keyboard/msd-keyboard-xkb.c

```
msd-keyboard-xkb.c:622:32: warning: cast between incompatible function types from ‘GdkFilterReturn (*)(GdkXEvent *, GdkEvent *)’ {aka ‘GdkFilterReturn (*)(void *, union _GdkEvent *)’} to ‘GdkFilterReturn (*)(GdkXEvent *, GdkEvent *, void *)’ {aka ‘GdkFilterReturn (*)(void>
622 |   gdk_window_add_filter (NULL, (GdkFilterFunc)
|                                ^
msd-keyboard-xkb.c: In function ‘msd_keyboard_xkb_shutdown’:
msd-keyboard-xkb.c:676:34: warning: cast between incompatible function types from ‘GdkFilterReturn (*)(GdkXEvent *, GdkEvent *)’ {aka ‘GdkFilterReturn (*)(void *, union _GdkEvent *)’} to ‘GdkFilterReturn (*)(GdkXEvent *, GdkEvent *, void *)’ {aka ‘GdkFilterReturn (*)(void>
676 |  gdk_window_remove_filter (NULL, (GdkFilterFunc)
|                                  ^
```

keyboard: Remove warning -Wcast-function-type

---

plugins/media-keys/msd-media-keys-manager.c

> The returned list should be freed with g_list_free(), after its elements have been unreffed with g_object_unref().
https://developer.gnome.org/gio/stable/GVolumeMonitor.html#g-volume-monitor-get-connected-drives

media-keys: memory leak

---

plugins/rfkill/rfkill-glib.c

```
rfkill-glib.c:360:25: warning: ‘g_memdup’ is deprecated: Use 'g_memdup2' instead [-Wdeprecated-declarations]
360 |                         event_ptr = g_memdup (&event, sizeof(event));
|                         ^~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:82,
from rfkill-glib.c:35:
/usr/include/glib-2.0/glib/gstrfuncs.h:257:23: note: declared here
257 | gpointer              g_memdup         (gconstpointer mem,
|                       ^~~~~~~~
```
```
rfkill-glib.c:443:17: warning: ‘g_memdup’ is deprecated: Use 'g_memdup2' instead [-Wdeprecated-declarations]
443 |                 event_ptr = g_memdup (&event, sizeof(event));
|                 ^~~~~~~~~
In file included from /usr/include/glib-2.0/glib.h:82,
from rfkill-glib.c:35: …
```

rfkill: g_memdup is dreprecated from glib 2.68

---

plugins/xsettings/msd-xsettings-manager.c

This makes it match Xft/DPI in XSETTINGS. Applications relying on Xft.dpi
on HiDPI screens will now work correctly.
Behavior is now consistent with GNOME, relevant commits from gsd:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/047f030235972fdab5e15aff484006caf914216a
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/25c7cc703118c69b224acf9c4f7af09a31f50a34

xsettings: Set Xft.dpi in X resources to scaled_dpi

---

plugins/datetime/msd-datetime-mechanism.c

```
CC=gcc CFLAGS="-ggdb3 -O0 -fsanitize=address" LDFLAGS="-fsanitize=address"  ./autogen.sh --prefix=/usr --enable-debug  --enable-compile-warnings=maximum && make &> make.log && sudo make install
```
```
LeakSanitizer: detected memory leaks
Direct leak of 7 byte(s) in 1 object(s) allocated from:
#0 0x7f7e2094393f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7f7e1f867b7f in g_malloc ../glib/gmem.c:106
#2 0x7f7e1f867ec2 in g_malloc_n ../glib/gmem.c:344
#3 0x7f7e1f88a1a5 in g_strdup ../glib/gstrfuncs.c:364
#4 0x4068b5 in check_can_do /home/robert/builddir.gcc/mate-settings-daemon/plugins/datetime/msd-datetime-mechanism.c:596
#5 0x406ae0 in msd_datetime_mechanism_can_set_time /home/robert/builddir.gcc/mate-settings-daemon/plugins/datetime/msd-datetime-mechanism.c:633
#6 …
```

datetime: fix memory leak

---

plugins/xrdb/msd-xrdb-manager.c

```
msd-xrdb-manager.c:73:33: warning: format specifies type 'unsigned short' but the argument has type 'int' [-Wformat]
color->red>>8,
^~~~~~~~~~~~~
msd-xrdb-manager.c:74:33: warning: format specifies type 'unsigned short' but the argument has type 'int' [-Wformat]
color->green>>8,
^~~~~~~~~~~~~~~
msd-xrdb-manager.c:75:33: warning: format specifies type 'unsigned short' but the argument has type 'int' [-Wformat]
color->blue>>8);
^~~~~~~~~~~~~~
```

xrdb: wrong type field in printf format string

---

plugins/housekeeping/msd-housekeeping-manager.c

It also fixes a SEGV when logging out MATE session because the cleanup functions were called twice.

housekeeping: disconnect manager's changed settings signal on finalize

---

mate-settings-daemon/main.c
plugins/rfkill/msd-rfkill-manager.c

```
main.c:70:16: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL }
^
--
msd-rfkill-manager.c:466:1: warning: missing field 'padding' initializer [-Wmissing-field-initializers]
};
^
```

Fix build warnings about missing field initializer

---

plugins/common/msd-osd-window.c
plugins/mouse/msd-timeline.c

```
CFLAGS="-Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
```
msd-osd-window.c:444:39: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
window->priv->is_composited = gdk_screen_is_composited (screen);
~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--
msd-timeline.c:649:16: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
priv->loop = loop;
~ ^~~~
```

Fix implicit conversion changes signedness: 'gboolean' to 'guint'

---

plugins/a11y-keyboard/msd-a11y-keyboard-atspi.c

Fix fairly large memory leak when beeping on keys while caps lock is enabled.  The libatspi2 docs and API were quite misleading, so I overlooked the fact the event parameter should be freed in the callback.
This changes the constness of the callback argument, which is new in libatspi2 2.40 -- yet the actual behavior didn't change, only the qualifier was removed, see [1].
This might however bring up a compiler warning when building against libatspi2 < 2.40;  but on the other hand it fixed build with clang >= 16, see #399.  As it is unlikely to build with clang >= 16 and libatspi2 < 2.40, I think it's a good compromise.
[1] https://gitlab.gnome.org/GNOME/at-spi2-core/-/commit/7dfb0b7fc2d1710ef7fad54f910fa4c6a5e3af17

a11y-keyboard-atspi: Fix memory leak

---

plugins/media-keys/msd-media-keys-manager.c
plugins/rfkill/msd-rfkill-manager.c

1. rename dbus name to "org.mate.SettingsDaemon", now there is only one dbus name called "org.mate.SettingsDaemon", you  can see the difference using `d-feet`.
2. allow `mate-settings-daemon --replace`

Gdbus rfkill

---

plugins/media-keys/msd-media-keys-manager.c

~~Before this patch:~~
~~press F1, yelp show the gnome desktop help documents~~
~~press WWW, browser show a blank page.~~
~~After this patch:~~
~~press F1, yelp show the mate desktop help documents~~
~~press WWW, browser show the mate-desktop website.~~
Open default application using async function

Open default application using async function

---

configure.ac
mate-settings-daemon/Makefile.am
plugins/a11y-keyboard/Makefile.am
plugins/background/Makefile.am
plugins/clipboard/Makefile.am
plugins/keyboard/Makefile.am
plugins/xrandr/Makefile.am
plugins/xsettings/Makefile.am

Many of the plugins have undefined references, but with GNU libtool it silently ignores the `-no-undefined` flag so the build succeeds. With slibtool it correctly sets `-Wl,--no-undefined` in the linker flags causing the build to fail.
Please view the commit messages for more details. The alternative to removing `-no-undefined` in the last commit is to turn most of `mate-settings-daemon` into a convenience library and link that into most of the plugins, but that doesn't seem correct.
This was reported for Gentoo: https://bugs.gentoo.org/922326

plugins: fix undefined references

---

data/org.mate.SettingsDaemon.plugins.media-keys.gschema.xml.in

The keybinding is alt+super+s.
This is my first contribution here, I am not sure how to verify my changes. Help appreciated.

add a keyboard shortcut to start a screen reader

---

configure.ac
data/mate-settings-daemon-uninstalled.pc.in
data/mate-settings-daemon.pc.in

We already switched the code over to using gdbus during the 1.27 development cycle. This removes three remnants

Remove remaining unused references to dbus-glib
